#+title: B. S. Tancham - My Emacs Configuration

* New Emacs Setup

Clone this repository into dir:

: ~/.emacs.d/init

Create init file in the default location:

: ~/.emacs.d/init.el

Init file contains one line only:

#+BEGIN_SRC elisp
(load-file "~/.emacs.d/init/init.el")
#+END_SRC

This loads my actual init file, which is in the version controlled
directory. That file loads all of the other config files.

** Installing use-package

If emacs is restarted at this point, it will crash because use-package is not
installed!

Eval this line to add the melpa package archive:

#+BEGIN_SRC elisp
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
#+END_SRC

Install use-package:

: M-x package-install <RET> use-package

Now restart emacs and use-package should download and install all other required
packages.

* Setup Snippets Collection

Clone the snippets repository: https://github.com/bstancham/bs-emacs-snippets

Put snippets here:

: ~/.emacs.d/snippets

* Setup Private Configuration

The main init file also loads another file which does private config (email
setup etc) and is not under version control.

Put any private configuration in this file:

: ~/.emacs.d/init-private/init-private.el

If this file exists then it will be loaded.

** Sample Private Init File
#+BEGIN_SRC elisp
;;;; SENDING EMAIL

;; NOTE: account login details are in ~/.authinfo - the format is like this...
;; (look up documentation from host for email smtp server address)
;; machine smtp.server.address login joe@joebloggs.com password PASSWORD

;; IMPORTANT! ~/.authinfo should be encrypted (~/.authinfo.gpg)

;; needs to be specified before the requiring smtpmail
(setq smtpmail-default-smtp-server "smtpserver")
(require 'smtpmail)
(setq send-mail-function 'smtpmail-send-it)

;; default mail identity (joe@joebloggs.com)
(setq user-full-name "Joe Bloggs"
      smtpmail-local-domain "joebloggs.com"
      user-mail-address (concat "joe@" smtpmail-local-domain))

;; sending mail (EXAMPLE SETUP - look for instructions from email server host)
(setq smtpmail-smtp-server "smtp.server.address"
      smtpmail-smtp-service 465
      smtpmail-stream-type 'ssl ; otherwise my host won't let me use the secure port 465
      smtpmail-smtp-user user-mail-address)
#+END_SRC
